- name: gather facts
  hosts: local
  connection: local
  ## ansible collecys the info of the target server, before it execute any other facts
  tasks:
  - name: facts
    ansible.builtin.debug:
     msg: "{{ ansible_facts }}"