- name: Install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.packages:
      msg: "{{ item }}"
    loop:
    - nginx
    - mysql
    - zip