- name: user creation
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: chech user exist or not
    ansible.builtin.debug: id roboshop
    register: user_output
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ user_output }}"